mysql: # mysql 配置
  host: "127.0.0.1"
  port: 3306
  user: "one"
  password: "pass"
  db_name: app_rocket
  pool_min_idle: 8 # 最小连接数
  pool_max_open: 32 # 最大连接数
  timeout_seconds: 15 # 连接超时时间单位秒

sqlite: # sqlite 配置
  db_url: "sqlite://app_rocket/data.sqlite3" # Sqlite3 数据库地址
  pool_min_idle: 8 # 最小连接数
  pool_max_open: 32 # 最大连接数
  timeout_seconds: 15 # 连接超时时间单位秒
