[package]
name = "watch_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"


[dev-dependencies]
cargo-watch = { version = "8.4" }
